In [ ]:
import numpy as np

arr_empty = np.empty((2, 2))
print("1. Empty array (2x2):")
print(arr_empty)
print()

arr_ones = np.ones((4, 2))
print("2. All ones array (4x2):")
print(arr_ones)
print()

arr_full = np.full((3, 3), 7, dtype=int)
print("3. Full array with fill value 7:")
print(arr_full)
print()

given_array = np.array([[1, 2], [3, 4]])
arr_zeros_like = np.zeros_like(given_array)
print("4. Zeros array with same shape and type as given array:")
print(arr_zeros_like)
print()

arr_ones_like = np.ones_like(given_array)
print("5. Ones array with same shape and type as given array:")
print(arr_ones_like)
print()

new_list = [1, 2, 3, 4]
np_array = np.array(new_list)
print("6. NumPy array from list:")
print(np_array)


1. Empty array (2x2):
[[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]

2. All ones array (4x2):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Full array with fill value 7:
[[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros array with same shape and type as given array:
[[0 0]
 [0 0]]

5. Ones array with same shape and type as given array:
[[1 1]
 [1 1]]

6. NumPy array from list:
[1 2 3 4]


In [ ]:
arr = np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
matrix = np.arange(9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
rand_arr = np.random.random(30)
print(rand_arr.mean())

0.5351076683902235


In [ ]:
rand_10x10 = np.random.random((10,10))
print(rand_10x10.min(), rand_10x10.max())


0.016413267845371893 0.9980212950748806


In [ ]:
zero_arr = np.zeros(10)
zero_arr[4] = 1
print(zero_arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
arr_rev = np.array([1,2,0,0,4,0])[::-1]
print(arr_rev)

[0 4 0 0 2 1]


In [ ]:
border = np.ones((5,5))
border[1:-1,1:-1] = 0
print(border)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
checker = np.zeros((8,8), dtype=int)
checker[1::2, ::2] = 1
checker[::2, 1::2] = 1
print(checker)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

print("x + y =\n", x + y)
print()

print("x - y =\n", x - y)
print()

print("x * 3 =\n", x * 3)
print()

print("x^2 =\n", x ** 2)
print()

print("Dot product of v and w:", np.dot(v, w))
print("Dot product of x and v:", np.dot(x, v))
print("Dot product of x and y:\n", np.dot(x, y))
print()

print("Concatenate x and y along row (axis=0):\n", np.concatenate((x, y), axis=0))
print("Concatenate v and w along column (as 2D arrays):\n", np.column_stack((v, w)))
print()

try:
    print(np.concatenate((x, v), axis=0))
except ValueError as e:
    print("Error:", e)
    print("Explanation: x is 2x2 and v is 1D array of size 2. They do not have the same number of dimensions, so direct concatenation fails.")


x + y =
 [[ 6  8]
 [10 13]]

x - y =
 [[-4 -4]
 [-4 -3]]

x * 3 =
 [[ 3  6]
 [ 9 15]]

x^2 =
 [[ 1  4]
 [ 9 25]]

Dot product of v and w: 219
Dot product of x and v: [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]

Concatenate x and y along row (axis=0):
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along column (as 2D arrays):
 [[ 9 11]
 [10 12]]

Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: x is 2x2 and v is 1D array of size 2. They do not have the same number of dimensions, so direct concatenation fails.


In [ ]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

I = np.dot(A, np.linalg.inv(A))
print("A * A^-1 =\n", I)
print()

AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB =\n", AB)
print("BA =\n", BA)
print("AB == BA:", np.array_equal(AB, BA))
print()

print("(AB)^T =\n", (AB).T)
print("B^T * A^T =\n", np.dot(B.T, A.T))
print("Check equality:", np.array_equal((AB).T, np.dot(B.T, A.T)))
print()

coeff = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
const = np.array([[-1], [-3], [9]])

X = np.dot(np.linalg.inv(coeff), const)
print("Solution using inverse method:\n", X)


A * A^-1 =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]
AB == BA: False

(AB)^T =
 [[23 51]
 [13 29]]
B^T * A^T =
 [[23 51]
 [13 29]]
Check equality: True

Solution using inverse method:
 [[ 2.]
 [ 1.]
 [-2.]]


In [1]:
import numpy as np
import time

size = 1_000_000

list1 = list(range(size))
list2 = list(range(size))
start = time.time()
list_add = [list1[i] + list2[i] for i in range(size)]
end = time.time()
print("Python list addition time:", end - start, "seconds")

arr1 = np.arange(size)
arr2 = np.arange(size)
start = time.time()
arr_add = arr1 + arr2
end = time.time()
print("NumPy array addition time:", end - start, "seconds")
print()

start = time.time()
list_mul = [list1[i] * list2[i] for i in range(size)]
end = time.time()
print("Python list multiplication time:", end - start, "seconds")

start = time.time()
arr_mul = arr1 * arr2
end = time.time()
print("NumPy array multiplication time:", end - start, "seconds")
print()

start = time.time()
dot_list = sum(list1[i] * list2[i] for i in range(size))
end = time.time()
print("Python list dot product time:", end - start, "seconds")

start = time.time()
dot_arr = np.dot(arr1, arr2)
end = time.time()
print("NumPy array dot product time:", end - start, "seconds")
print()

matrix_size = 1000

mat1 = [[i + j for j in range(matrix_size)] for i in range(matrix_size)]
mat2 = [[i + j for j in range(matrix_size)] for i in range(matrix_size)]
start = time.time()
result = [[sum(mat1[i][k] * mat2[k][j] for k in range(matrix_size)) for j in range(matrix_size)]
          for i in range(matrix_size)]
end = time.time()
print("Python list matrix multiplication time:", end - start, "seconds")

matA = np.arange(matrix_size*matrix_size).reshape(matrix_size, matrix_size)
matB = np.arange(matrix_size*matrix_size).reshape(matrix_size, matrix_size)
start = time.time()
result_np = np.dot(matA, matB)
end = time.time()
print("NumPy array matrix multiplication time:", end - start, "seconds")


Python list addition time: 0.12112855911254883 seconds
NumPy array addition time: 0.007261753082275391 seconds

Python list multiplication time: 0.1370251178741455 seconds
NumPy array multiplication time: 0.0034253597259521484 seconds

Python list dot product time: 0.11174297332763672 seconds
NumPy array dot product time: 0.0026960372924804688 seconds

Python list matrix multiplication time: 200.59225130081177 seconds
NumPy array matrix multiplication time: 1.8274919986724854 seconds
